In [4]:
%matplotlib inline

import json
import pandas as pd
import numpy as np

In [2]:
all_matches = pd.read_csv('all_t20i_05-16.csv')
all_matches = all_matches.sort('date', ascending = False)
matches = all_matches.match_id.values

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app

In [3]:
def f(i):
    return i['bat'], i['bowl'], i['o_u'], i['ovr'], i['r'], i['r_t'], i['x'], i['y'], i['z']

In [6]:
import os.path
failed_ids = []

for idx, match_id in enumerate(matches):
    try:
        wicket_data = json.load(open('data/%s-pie-wickets.json'%(match_id)))
        df = pd.io.json.read_json('data/%s-wagon-inning-1.json'%(match_id), dtype=False)    
        df['inning'] = 1
        df['batting_team'] = wicket_data['t1']['n']
        df['bowling_team'] = wicket_data['t2']['n']

        df2 = pd.io.json.read_json('data/%s-wagon-inning-2.json'%(match_id), dtype=False)
        df2['inning'] = 2
        df2['batting_team'] = wicket_data['t2']['n']
        df2['bowling_team'] = wicket_data['t1']['n']

        df['batsman'], df['bowler'], df['ball_num'], df['ovr'], df['runs_batter'], df['runs_w_extras'], df['x'], df['y'], df['z'] = zip(*df.runs.apply(f))
        df2['batsman'], df2['bowler'], df2['ball_num'], df2['ovr'], df2['runs_batter'], df2['runs_w_extras'], df2['x'], df2['y'], df2['z'] = zip(*df2.runs.apply(f))

        for param in ['ball_num', 'ovr', 'runs_batter', 'runs_w_extras', 'x', 'y', 'z']:
            df[param] = df[param].astype(float)
            df2[param] = df2[param].astype(float)

        from collections import defaultdict
        dismissals = defaultdict(dict)

        for i in wicket_data['t1']['w']:
            dismissals[float(i['ovr'])] = {'inning': 1, 'how': i['how'], 'ovr': float(i['ovr']), 'batsman': i['out'], 'bowler': i['outby']}

        for i in wicket_data['t2']['w']:
            dismissals[float(i['ovr'])] = {'inning': 2, 'how': i['how'], 'ovr': float(i['ovr']), 'batsman': i['out'], 'bowler': i['outby']}

        def add_wickets(inning, ovr, batsman, extras, unique, dismissals = dismissals):
            #Note: a run-out on a no-ball or wide will be double-counted
            if ovr in dismissals and dismissals[ovr]['inning'] == inning:
                if unique == 'True':
                    return True, dismissals[ovr]['how'], dismissals[ovr]['batsman']
                else:
                    if dismissals[ovr]['how'] != 'run out':
                        if extras == 0:
                            return True, dismissals[ovr]['how'], dismissals[ovr]['batsman']
                        else:
                            return False, np.nan, np.nan
                    else:
                        return True, dismissals[ovr]['how'], dismissals[ovr]['batsman'] #think of a better way later
            return False, np.nan, np.nan

        val_count_1 = df.ovr.value_counts()
        val_count_2 = df2.ovr.value_counts()

        def get_unique_1(i):
            if val_count_1[i] == 1:
                return True
            return False

        def get_unique_2(i):
            if val_count_2[i] == 1:
                return True
            return False

        df['ovr_unique'] = df.ovr.apply(get_unique_1)
        df2['ovr_unique'] = df2.ovr.apply(get_unique_2)
        df['extras'] = df['runs_w_extras'] - df['runs_batter']
        df2['extras'] = df2['runs_w_extras'] - df2['runs_batter']
        df['wicket'], df['wicket_method'], df['who_out'] = zip(*df.apply(lambda row: add_wickets(row['inning'], row['ovr'], row['batsman'], row['extras'], row['ovr_unique']), axis=1))
        df2['wicket'], df2['wicket_method'], df2['who_out'] = zip(*df2.apply(lambda row: add_wickets(row['inning'], row['ovr'], row['batsman'], row['extras'], row['ovr_unique']), axis=1))
        df['match_id'] = match_id
        df2['match_id'] = match_id

        df['cumul_runs'] = df['runs_w_extras'].cumsum()
        df['cumul_wickets'] = df['wicket'].cumsum()
        df['cumul_balls'] = df['ovr'].apply(lambda x: 6*int(x) + int(10*x)%10)
        df2['cumul_runs'] = df2['runs_w_extras'].cumsum()
        df2['cumul_wickets'] = df2['wicket'].cumsum()
        df2['cumul_balls'] = df2['ovr'].apply(lambda x: 6*int(x) + int(10*x)%10)
        
        player_db = {}
        inn_1_batting_order = {}
        inn_2_batting_order = {}
        for idx__, d in enumerate(wicket_data['t1']['p']):
            player_db.update(d)
            inn_1_batting_order[d.keys()[0]] = idx__+1
        for idx__, d in enumerate(wicket_data['t2']['p']):
            player_db.update(d)
            inn_2_batting_order[d.keys()[0]] = idx__+1

        def get_name(i):
            return player_db.get(i, None)

        df['batsman_name'] = df['batsman'].apply(get_name)
        df['bowler_name'] = df['bowler'].apply(get_name)
        df['who_out'] = df['who_out'].apply(get_name)
        df['batting_order'] = df['batsman'].apply(inn_1_batting_order.get)
        
        df2['batsman_name'] = df2['batsman'].apply(get_name)
        df2['bowler_name'] = df2['bowler'].apply(get_name)
        df2['who_out'] = df2['who_out'].apply(get_name)
        df2['batting_order'] = df2['batsman'].apply(inn_2_batting_order.get)
        
        df = df.append(df2)    
        df = df.drop('runs', axis=1)
        df = df.reset_index(drop=True)

        if os.path.isfile('data/%s_ball_details.txt'%(match_id)):
            try:
                with open('data/%s_ball_details.txt'%(match_id), 'r') as fil:
                    a = eval(fil.read()[8:-2])
                l = []
                for i in a[0]['data']:
                    temp = i.values()[0].split(',')
                    l.append({'ball_speed': temp[3], 'landing_y': temp[4], 'landing_x': temp[5], 'bat_right_handed': temp[6],
                         'ended_x': temp[7], 'ended_y': temp[8]})
                df2 = pd.DataFrame(l)
                if len(df2) == len(df):
                    df = df.join(df2)
                    cols = ['inning', 'batting_team', 'bowling_team', 'batsman', 'bowler', 'batsman_name', 'batting_order',
                        'bowler_name', 'bat_right_handed', 'ovr', 'runs_batter', 'runs_w_extras', 'extras',
                        'x', 'y', 'z', 'landing_x', 'landing_y', 'ended_x', 'ended_y', 'ball_speed', 'cumul_runs',
                        'cumul_wickets', 'cumul_balls', 'wicket', 'wicket_method', 'who_out']
                else:
                    print 'discrepancy', match_id
                    cols = ['inning', 'batting_team', 'bowling_team', 'batsman', 'bowler', 'batsman_name', 'batting_order',
                    'bowler_name', 'ovr', 'runs_batter', 'runs_w_extras', 'extras',
                    'x', 'y', 'z', 'cumul_runs', 'cumul_wickets', 'cumul_balls', 'wicket', 'wicket_method', 'who_out']
            except:
                cols = ['inning', 'batting_team', 'bowling_team', 'batsman', 'bowler', 'batsman_name', 'batting_order',
                    'bowler_name', 'ovr', 'runs_batter', 'runs_w_extras', 'extras',
                    'x', 'y', 'z', 'cumul_runs', 'cumul_wickets', 'cumul_balls', 'wicket', 'wicket_method', 'who_out']
        df = df[cols]
        df.to_csv('cleaned_data/%s_summary.csv'%(match_id))
        print 'success', idx, len(matches)
    except:
        print 'failed', idx, match_id, len(matches)
        failed_ids.append(int(match_id))

success 0 505
success 1 505
success 2 505
success 3 505
success 4 505
success 5 505
success 6 505
success 7 505
success 8 505
success 9 505
success 10 505
success 11 505
success 12 505
success 13 505
success 14 505
success 15 505
success 16 505
success 17 505
success 18 505
success 19 505
success 20 505
success 21 505
success 22 505
success 23 505
success 24 505
success 25 505
success 26 505
success 27 505
success 28 505
success 29 505
success 30 505
success 31 505
success 32 505
success 33 505
success 34 505
success 35 505
success 36 505
success 37 505
success 38 505
success 39 505
success 40 505
success 41 505
success 42 505
success 43 505
success 44 505
success 45 505
success 46 505
success 47 505
success 48 505
success 49 505
success 50 505
success 51 505
success 52 505
success 53 505
success 54 505
success 55 505
success 56 505
success 57 505
success 58 505
success 59 505
success 60 505
success 61 505
success 62 505
success 63 505
success 64 505
success 65 505
success 66 505
success 67 505
success 68 505
success 69 505
success 70 505
success 71 505
success 72 505
success 73 505
success 74 505
success 75 505
success 76 505
success 77 505
success 78 505
success 79 505
success 80 505
success 81 505
success 82 505
success 83 505
success 84 505
success 85 505
success 86 505
success 87 505
discrepancy 817203
success 88 505
success 89 505
success 90 505
success 91 505
success 92 505
success 93 505
success 94 505
success 95 505
success 96 505
success 97 505
success 98 505
success 99 505
success 100 505
success 101 505
success 102 505
success 103 505
success 104 505
success 105 505
success 106 505
success 107 505
success 108 505
success 109 505
success 110 505
success 111 505
success 112 505
success 113 505
success 114 505
success 115 505
success 116 505
success 117 505
success 118 505
success 119 505
success 120 505
success 121 505
success 122 505
success 123 505
success 124 505
success 125 505
success 126 505
success 127 505
success 128 505
success 129 505
success 130 505
success 131 505
success 132 505
success 133 505
success 134 505
success 135 505
success 136 505
success 137 505
success 138 505
success 139 505
success 140 505
success 141 505
success 142 505
success 143 505
success 144 505
success 145 505
success 146 505
success 147 505
success 148 505
success 149 505
success 150 505
success 151 505
success 152 505
success 153 505
success 154 505
success 155 505
success 156 505
success 157 505
success 158 505
success 159 505
success 160 505
success 161 505
success 162 505
success 163 505
success 164 505
success 165 505
success 166 505
success 167 505
success 168 505
success 169 505
success 170 505
success 171 505
success 172 505
success 173 505
success 174 505
success 175 505
success 176 505
success 177 505
failed 178 660107 505
success 179 505
success 180 505
success 181 505
success 182 505
success 183 505
success 184 505
success 185 505
success 186 505
success 187 505
success 188 505
success 189 505
success 190 505
success 191 505
success 192 505
success 193 505
success 194 505
success 195 505
success 196 505
success 197 505
success 198 505
success 199 505
success 200 505
success 201 505
success 202 505
success 203 505
success 204 505
success 205 505
success 206 505
success 207 505
success 208 505
success 209 505
success 210 505
success 211 505
success 212 505
success 213 505
success 214 505
success 215 505
success 216 505
success 217 505
success 218 505
success 219 505
success 220 505
success 221 505
success 222 505
success 223 505
success 224 505
success 225 505
success 226 505
success 227 505
success 228 505
success 229 505
success 230 505
success 231 505
success 232 505
success 233 505
success 234 505
success 235 505
success 236 505
success 237 505
success 238 505
success 239 505
success 240 505
success 241 505
success 242 505
discrepancy 533276
success 243 505
success 244 505
success 245 505
success 246 505
success 247 505
success 248 505
success 249 505
discrepancy 571150
success 250 505
success 251 505
success 252 505
success 253 505
discrepancy 564786
success 254 505
success 255 505
success 256 505
success 257 505
success 258 505
success 259 505
success 260 505
discrepancy 560922
success 261 505
success 262 505
success 263 505
success 264 505
success 265 505
success 266 505
success 267 505
success 268 505
success 269 505
success 270 505
success 271 505
success 272 505
success 273 505
success 274 505
success 275 505
success 276 505
success 277 505
success 278 505
success 279 505
success 280 505
success 281 505
success 282 505
success 283 505
success 284 505
success 285 505
success 286 505
success 287 505
success 288 505
success 289 505
success 290 505
success 291 505
discrepancy 518954
success 292 505
success 293 505
success 294 505
success 295 505
success 296 505
success 297 505
success 298 505
success 299 505
success 300 505
success 301 505
success 302 505
success 303 505
success 304 505
success 305 505
success 306 505
success 307 505
discrepancy 474466
success 308 505
success 309 505
success 310 505
success 311 505
success 312 505
discrepancy 463149
success 313 505
success 314 505
success 315 505
success 316 505
success 317 505
success 318 505
success 319 505
success 320 505
success 321 505
success 322 505
success 323 505
success 324 505
success 325 505
success 326 505
success 327 505
success 328 505
success 329 505
success 330 505
success 331 505
success 332 505
success 333 505
success 334 505
success 335 505
success 336 505
success 337 505
success 338 505
success 339 505
success 340 505
success 341 505
success 342 505
success 343 505
success 344 505
success 345 505
success 346 505
success 347 505
success 348 505
success 349 505
success 350 505
success 351 505
success 352 505
success 353 505
success 354 505
success 355 505
success 356 505
success 357 505
success 358 505
success 359 505
success 360 505
success 361 505
success 362 505
success 363 505
success 364 505
success 365 505
success 366 505
success 367 505
success 368 505
success 369 505
success 370 505
success 371 505
success 372 505
success 373 505
success 374 505
success 375 505
success 376 505
success 377 505
success 378 505
success 379 505
success 380 505
success 381 505
success 382 505
success 383 505
success 384 505
success 385 505
success 386 505
success 387 505
success 388 505
success 389 505
success 390 505
success 391 505
success 392 505
success 393 505
success 394 505
success 395 505
success 396 505
success 397 505
success 398 505
success 399 505
success 400 505
success 401 505
success 402 505
success 403 505
success 404 505
success 405 505
success 406 505
success 407 505
success 408 505
success 409 505
success 410 505
success 411 505
success 412 505
success 413 505
success 414 505
success 415 505
success 416 505
success 417 505
success 418 505
success 419 505
success 420 505
success 421 505
success 422 505
success 423 505
success 424 505
success 425 505
success 426 505
success 427 505
success 428 505
success 429 505
success 430 505
success 431 505
success 432 505
success 433 505
success 434 505
success 435 505
success 436 505
success 437 505
success 438 505
success 439 505
success 440 505
success 441 505
success 442 505
success 443 505
success 444 505
success 445 505
success 446 505
success 447 505
success 448 505
success 449 505
success 450 505
success 451 505
success 452 505
success 453 505
success 454 505
success 455 505
success 456 505
success 457 505
success 458 505
success 459 505
success 460 505
success 461 505
success 462 505
success 463 505
success 464 505
success 465 505
success 466 505
success 467 505
success 468 505
success 469 505
success 470 505
success 471 505
success 472 505
success 473 505
success 474 505
success 475 505
success 476 505
success 477 505
success 478 505
success 479 505
success 480 505
success 481 505
success 482 505
success 483 505
success 484 505
success 485 505
success 486 505
success 487 505
success 488 505
success 489 505
success 490 505
success 491 505
success 492 505
success 493 505
success 494 505
success 495 505
failed 496 264065 505
success 497 505
success 498 505
success 499 505
success 500 505
success 501 505
success 502 505
success 503 505
success 504 505

### List of matches that were not parsed

In [7]:
all_matches[all_matches.match_id.isin(failed_ids)]

,Unnamed: 0,team1_name,team2_name,team1_id,team2_id,ground_name,ground_id,match_id,date
326,326,Afghanistan,Netherlands,40,15,Sharjah,59392,660107,2013-11-15
8,8,Bangladesh,Zimbabwe,25,9,Khulna,56691,264065,2006-11-28